### ISSUE TITLE
correct bubbel sort algorithm

### ISSUE THREAD

**Issue by bobby1708** [bobby1708/DS_Algo#3]
correct bubbel sort algorithm

**Comment by shikhar8434** [comment]
okay i am on it

**Comment by Avantikaa** [comment]
Hi @bobby1708 I would like to work on this. Can you assign this to me?

**Comment by shikhar8434** [comment]
can i also add some Data structure questions?

**Comment by Procoder16** [comment]
@bobby1708 Sir, I would like to contribute to this.

Can you please assign me this.

**Comment by namitmalasi** [comment]
I would like to contribute to this issue.

**Comment by psymbio** [comment]
Hey @bobby1708 I'd like to add in more data structures as well. Please consider the pull request.

**Comment by bobby1708** [comment]
Any in Can contribute

**Comment by bobby1708** [comment]
Anyone can contribute

**Comment by psymbio** [comment]
Did you accept pull requests?
